# Menus
menu:
  主页: .
  归档: ./archives
  分类: ./categories
  标签: ./tags
  关于: ./about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: css/images/logo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/avatar.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Hao Yin
        author_title: 只想简简单单的做自己
        location: shanghai, China
        follow: https://github.com/569258yin/
    highlight: monokai  #monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: css/images/logo.png # path to favicon 网页标题显示的图片
    social_links:
        github: http://github.com/569258yin/569258yin.github.io
        weibo: /
        facebook: /
        gg-circle: https://www.zhihu.com/people/yin-hao-45-22
        rss: /atom.xml
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    #disqus:  # enter disqus shortname here
    duoshuo: haoyinblog # enter duoshuo shortname here
    #youyan: # enter youyan uid here

# Share
share: bdshare # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: d14fa115c77b4d5f7a9c2a47c2153feb # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
